package com.starsgroupchina.credit.bean.model;

import com.starsgroupchina.common.base.BaseExample;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NumberRuleExample extends BaseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private String additionalWhere;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public NumberRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setAdditionalWhere(String additionalWhere) {
        this.additionalWhere = additionalWhere;
    }

    public String getAdditionalWhere() {
        return additionalWhere;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(Integer value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(Integer value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(Integer value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(Integer value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(Integer value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<Integer> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<Integer> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(Integer value1, Integer value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andNoNameIsNull() {
            addCriterion("no_name is null");
            return (Criteria) this;
        }

        public Criteria andNoNameIsNotNull() {
            addCriterion("no_name is not null");
            return (Criteria) this;
        }

        public Criteria andNoNameEqualTo(String value) {
            addCriterion("no_name =", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameNotEqualTo(String value) {
            addCriterion("no_name <>", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameGreaterThan(String value) {
            addCriterion("no_name >", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameGreaterThanOrEqualTo(String value) {
            addCriterion("no_name >=", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameLessThan(String value) {
            addCriterion("no_name <", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameLessThanOrEqualTo(String value) {
            addCriterion("no_name <=", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameLike(String value) {
            addCriterion("no_name like", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameNotLike(String value) {
            addCriterion("no_name not like", value, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameIn(List<String> values) {
            addCriterion("no_name in", values, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameNotIn(List<String> values) {
            addCriterion("no_name not in", values, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameBetween(String value1, String value2) {
            addCriterion("no_name between", value1, value2, "noName");
            return (Criteria) this;
        }

        public Criteria andNoNameNotBetween(String value1, String value2) {
            addCriterion("no_name not between", value1, value2, "noName");
            return (Criteria) this;
        }

        public Criteria andNoPrefixIsNull() {
            addCriterion("no_prefix is null");
            return (Criteria) this;
        }

        public Criteria andNoPrefixIsNotNull() {
            addCriterion("no_prefix is not null");
            return (Criteria) this;
        }

        public Criteria andNoPrefixEqualTo(String value) {
            addCriterion("no_prefix =", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixNotEqualTo(String value) {
            addCriterion("no_prefix <>", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixGreaterThan(String value) {
            addCriterion("no_prefix >", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixGreaterThanOrEqualTo(String value) {
            addCriterion("no_prefix >=", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixLessThan(String value) {
            addCriterion("no_prefix <", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixLessThanOrEqualTo(String value) {
            addCriterion("no_prefix <=", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixLike(String value) {
            addCriterion("no_prefix like", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixNotLike(String value) {
            addCriterion("no_prefix not like", value, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixIn(List<String> values) {
            addCriterion("no_prefix in", values, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixNotIn(List<String> values) {
            addCriterion("no_prefix not in", values, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixBetween(String value1, String value2) {
            addCriterion("no_prefix between", value1, value2, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoPrefixNotBetween(String value1, String value2) {
            addCriterion("no_prefix not between", value1, value2, "noPrefix");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatIsNull() {
            addCriterion("no_date_format is null");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatIsNotNull() {
            addCriterion("no_date_format is not null");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatEqualTo(String value) {
            addCriterion("no_date_format =", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatNotEqualTo(String value) {
            addCriterion("no_date_format <>", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatGreaterThan(String value) {
            addCriterion("no_date_format >", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatGreaterThanOrEqualTo(String value) {
            addCriterion("no_date_format >=", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatLessThan(String value) {
            addCriterion("no_date_format <", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatLessThanOrEqualTo(String value) {
            addCriterion("no_date_format <=", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatLike(String value) {
            addCriterion("no_date_format like", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatNotLike(String value) {
            addCriterion("no_date_format not like", value, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatIn(List<String> values) {
            addCriterion("no_date_format in", values, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatNotIn(List<String> values) {
            addCriterion("no_date_format not in", values, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatBetween(String value1, String value2) {
            addCriterion("no_date_format between", value1, value2, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoDateFormatNotBetween(String value1, String value2) {
            addCriterion("no_date_format not between", value1, value2, "noDateFormat");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartIsNull() {
            addCriterion("no_number_start is null");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartIsNotNull() {
            addCriterion("no_number_start is not null");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartEqualTo(Integer value) {
            addCriterion("no_number_start =", value, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartNotEqualTo(Integer value) {
            addCriterion("no_number_start <>", value, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartGreaterThan(Integer value) {
            addCriterion("no_number_start >", value, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartGreaterThanOrEqualTo(Integer value) {
            addCriterion("no_number_start >=", value, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartLessThan(Integer value) {
            addCriterion("no_number_start <", value, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartLessThanOrEqualTo(Integer value) {
            addCriterion("no_number_start <=", value, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartIn(List<Integer> values) {
            addCriterion("no_number_start in", values, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartNotIn(List<Integer> values) {
            addCriterion("no_number_start not in", values, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartBetween(Integer value1, Integer value2) {
            addCriterion("no_number_start between", value1, value2, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberStartNotBetween(Integer value1, Integer value2) {
            addCriterion("no_number_start not between", value1, value2, "noNumberStart");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthIsNull() {
            addCriterion("no_number_length is null");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthIsNotNull() {
            addCriterion("no_number_length is not null");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthEqualTo(Integer value) {
            addCriterion("no_number_length =", value, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthNotEqualTo(Integer value) {
            addCriterion("no_number_length <>", value, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthGreaterThan(Integer value) {
            addCriterion("no_number_length >", value, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("no_number_length >=", value, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthLessThan(Integer value) {
            addCriterion("no_number_length <", value, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthLessThanOrEqualTo(Integer value) {
            addCriterion("no_number_length <=", value, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthIn(List<Integer> values) {
            addCriterion("no_number_length in", values, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthNotIn(List<Integer> values) {
            addCriterion("no_number_length not in", values, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthBetween(Integer value1, Integer value2) {
            addCriterion("no_number_length between", value1, value2, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andNoNumberLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("no_number_length not between", value1, value2, "noNumberLength");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueIsNull() {
            addCriterion("current_date_value is null");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueIsNotNull() {
            addCriterion("current_date_value is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueEqualTo(String value) {
            addCriterion("current_date_value =", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueNotEqualTo(String value) {
            addCriterion("current_date_value <>", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueGreaterThan(String value) {
            addCriterion("current_date_value >", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueGreaterThanOrEqualTo(String value) {
            addCriterion("current_date_value >=", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueLessThan(String value) {
            addCriterion("current_date_value <", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueLessThanOrEqualTo(String value) {
            addCriterion("current_date_value <=", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueLike(String value) {
            addCriterion("current_date_value like", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueNotLike(String value) {
            addCriterion("current_date_value not like", value, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueIn(List<String> values) {
            addCriterion("current_date_value in", values, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueNotIn(List<String> values) {
            addCriterion("current_date_value not in", values, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueBetween(String value1, String value2) {
            addCriterion("current_date_value between", value1, value2, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentDateValueNotBetween(String value1, String value2) {
            addCriterion("current_date_value not between", value1, value2, "currentDateValue");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberIsNull() {
            addCriterion("current_number is null");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberIsNotNull() {
            addCriterion("current_number is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberEqualTo(String value) {
            addCriterion("current_number =", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberNotEqualTo(String value) {
            addCriterion("current_number <>", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberGreaterThan(String value) {
            addCriterion("current_number >", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberGreaterThanOrEqualTo(String value) {
            addCriterion("current_number >=", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberLessThan(String value) {
            addCriterion("current_number <", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberLessThanOrEqualTo(String value) {
            addCriterion("current_number <=", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberLike(String value) {
            addCriterion("current_number like", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberNotLike(String value) {
            addCriterion("current_number not like", value, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberIn(List<String> values) {
            addCriterion("current_number in", values, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberNotIn(List<String> values) {
            addCriterion("current_number not in", values, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberBetween(String value1, String value2) {
            addCriterion("current_number between", value1, value2, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentNumberNotBetween(String value1, String value2) {
            addCriterion("current_number not between", value1, value2, "currentNumber");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("modify_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("modify_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Integer value) {
            addCriterion("modify_user_id =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Integer value) {
            addCriterion("modify_user_id <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Integer value) {
            addCriterion("modify_user_id >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Integer value) {
            addCriterion("modify_user_id <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Integer> values) {
            addCriterion("modify_user_id in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Integer> values) {
            addCriterion("modify_user_id not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("modify_user is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("modify_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("modify_user =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("modify_user <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("modify_user >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("modify_user <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("modify_user <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("modify_user like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("modify_user not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("modify_user in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("modify_user not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("modify_user between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("modify_user not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table number_rule
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table number_rule
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}