package com.starsgroupchina.credit.bean.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.starsgroupchina.common.base.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

@ApiModel
public class Product extends BaseModel implements Serializable {
    @ApiModelProperty("id")
    private Integer id;

    @ApiModelProperty("机构ID")
    private Integer orgId;

    @ApiModelProperty("类别ID")
    private Integer categoryId;

    @ApiModelProperty("模型ID")
    private Integer modelId;

    @ApiModelProperty("政策ID")
    private Integer policyId;

    @ApiModelProperty("产品名称")
    private String title;

    @ApiModelProperty("进件是否做交叉互审：1是；0否")
    private Short auditCross;

    @ApiModelProperty("自动审核: 1 是；0 否")
    private Short auditAuto;

    @ApiModelProperty("人工审核:1 是；0 否")
    private Short auditManual;

    @ApiModelProperty("人工复核:1 是；0 否")
    private Short auditManualRecheck;

    @ApiModelProperty("复核小组角色")
    private Integer auditRecheckRoleId;

    @ApiModelProperty("审核小组角色")
    private Integer auditRoleId;

    @ApiModelProperty("大峰报告过期时间")
    private Integer dfTime;

    @ApiModelProperty("是否需要大峰报告（0、需要，1、不需要)")
    private Short dfReport;

    @ApiModelProperty("是否需要同盾报告(0、需要，1、不需要)")
    private Short tdReport;

    @ApiModelProperty("同盾数据验证id")
    private Integer tdValidDataId;

    @ApiModelProperty("")
    private Integer tdTime;

    @ApiModelProperty("是否需要前海征信(0、需要，1、不需要)")
    private Short qhzxReport;

    @ApiModelProperty("前海数据验证id")
    private Integer qhValidDataId;

    @ApiModelProperty("前海征信过期时间")
    private Integer qhzxTime;

    @ApiModelProperty("表单ID")
    private Integer formId;

    @ApiModelProperty("建议金额（1分=多少钱）")
    private Double adviseAmount;

    @ApiModelProperty("0,正常，1禁用，-1删除")
    private Short status;

    @ApiModelProperty("顶级机构ID")
    private Integer headOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOrgId() {
        return orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getModelId() {
        return modelId;
    }

    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    public Integer getPolicyId() {
        return policyId;
    }

    public void setPolicyId(Integer policyId) {
        this.policyId = policyId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    public Short getAuditCross() {
        return auditCross;
    }

    public void setAuditCross(Short auditCross) {
        this.auditCross = auditCross;
    }

    public Short getAuditAuto() {
        return auditAuto;
    }

    public void setAuditAuto(Short auditAuto) {
        this.auditAuto = auditAuto;
    }

    public Short getAuditManual() {
        return auditManual;
    }

    public void setAuditManual(Short auditManual) {
        this.auditManual = auditManual;
    }

    public Short getAuditManualRecheck() {
        return auditManualRecheck;
    }

    public void setAuditManualRecheck(Short auditManualRecheck) {
        this.auditManualRecheck = auditManualRecheck;
    }

    public Integer getAuditRecheckRoleId() {
        return auditRecheckRoleId;
    }

    public void setAuditRecheckRoleId(Integer auditRecheckRoleId) {
        this.auditRecheckRoleId = auditRecheckRoleId;
    }

    public Integer getAuditRoleId() {
        return auditRoleId;
    }

    public void setAuditRoleId(Integer auditRoleId) {
        this.auditRoleId = auditRoleId;
    }

    public Integer getDfTime() {
        return dfTime;
    }

    public void setDfTime(Integer dfTime) {
        this.dfTime = dfTime;
    }

    public Short getDfReport() {
        return dfReport;
    }

    public void setDfReport(Short dfReport) {
        this.dfReport = dfReport;
    }

    public Short getTdReport() {
        return tdReport;
    }

    public void setTdReport(Short tdReport) {
        this.tdReport = tdReport;
    }

    public Integer getTdValidDataId() {
        return tdValidDataId;
    }

    public void setTdValidDataId(Integer tdValidDataId) {
        this.tdValidDataId = tdValidDataId;
    }

    public Integer getTdTime() {
        return tdTime;
    }

    public void setTdTime(Integer tdTime) {
        this.tdTime = tdTime;
    }

    public Short getQhzxReport() {
        return qhzxReport;
    }

    public void setQhzxReport(Short qhzxReport) {
        this.qhzxReport = qhzxReport;
    }

    public Integer getQhValidDataId() {
        return qhValidDataId;
    }

    public void setQhValidDataId(Integer qhValidDataId) {
        this.qhValidDataId = qhValidDataId;
    }

    public Integer getQhzxTime() {
        return qhzxTime;
    }

    public void setQhzxTime(Integer qhzxTime) {
        this.qhzxTime = qhzxTime;
    }

    public Integer getFormId() {
        return formId;
    }

    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    public Double getAdviseAmount() {
        return adviseAmount;
    }

    public void setAdviseAmount(Double adviseAmount) {
        this.adviseAmount = adviseAmount;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Integer getHeadOrgId() {
        return headOrgId;
    }

    public void setHeadOrgId(Integer headOrgId) {
        this.headOrgId = headOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        Product other = (Product) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getModelId() == null ? other.getModelId() == null : this.getModelId().equals(other.getModelId()))
            && (this.getPolicyId() == null ? other.getPolicyId() == null : this.getPolicyId().equals(other.getPolicyId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getAuditCross() == null ? other.getAuditCross() == null : this.getAuditCross().equals(other.getAuditCross()))
            && (this.getAuditAuto() == null ? other.getAuditAuto() == null : this.getAuditAuto().equals(other.getAuditAuto()))
            && (this.getAuditManual() == null ? other.getAuditManual() == null : this.getAuditManual().equals(other.getAuditManual()))
            && (this.getAuditManualRecheck() == null ? other.getAuditManualRecheck() == null : this.getAuditManualRecheck().equals(other.getAuditManualRecheck()))
            && (this.getAuditRecheckRoleId() == null ? other.getAuditRecheckRoleId() == null : this.getAuditRecheckRoleId().equals(other.getAuditRecheckRoleId()))
            && (this.getAuditRoleId() == null ? other.getAuditRoleId() == null : this.getAuditRoleId().equals(other.getAuditRoleId()))
            && (this.getDfTime() == null ? other.getDfTime() == null : this.getDfTime().equals(other.getDfTime()))
            && (this.getDfReport() == null ? other.getDfReport() == null : this.getDfReport().equals(other.getDfReport()))
            && (this.getTdReport() == null ? other.getTdReport() == null : this.getTdReport().equals(other.getTdReport()))
            && (this.getTdValidDataId() == null ? other.getTdValidDataId() == null : this.getTdValidDataId().equals(other.getTdValidDataId()))
            && (this.getTdTime() == null ? other.getTdTime() == null : this.getTdTime().equals(other.getTdTime()))
            && (this.getQhzxReport() == null ? other.getQhzxReport() == null : this.getQhzxReport().equals(other.getQhzxReport()))
            && (this.getQhValidDataId() == null ? other.getQhValidDataId() == null : this.getQhValidDataId().equals(other.getQhValidDataId()))
            && (this.getQhzxTime() == null ? other.getQhzxTime() == null : this.getQhzxTime().equals(other.getQhzxTime()))
            && (this.getFormId() == null ? other.getFormId() == null : this.getFormId().equals(other.getFormId()))
            && (this.getAdviseAmount() == null ? other.getAdviseAmount() == null : this.getAdviseAmount().equals(other.getAdviseAmount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getHeadOrgId() == null ? other.getHeadOrgId() == null : this.getHeadOrgId().equals(other.getHeadOrgId()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getModelId() == null) ? 0 : getModelId().hashCode());
        result = prime * result + ((getPolicyId() == null) ? 0 : getPolicyId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getAuditCross() == null) ? 0 : getAuditCross().hashCode());
        result = prime * result + ((getAuditAuto() == null) ? 0 : getAuditAuto().hashCode());
        result = prime * result + ((getAuditManual() == null) ? 0 : getAuditManual().hashCode());
        result = prime * result + ((getAuditManualRecheck() == null) ? 0 : getAuditManualRecheck().hashCode());
        result = prime * result + ((getAuditRecheckRoleId() == null) ? 0 : getAuditRecheckRoleId().hashCode());
        result = prime * result + ((getAuditRoleId() == null) ? 0 : getAuditRoleId().hashCode());
        result = prime * result + ((getDfTime() == null) ? 0 : getDfTime().hashCode());
        result = prime * result + ((getDfReport() == null) ? 0 : getDfReport().hashCode());
        result = prime * result + ((getTdReport() == null) ? 0 : getTdReport().hashCode());
        result = prime * result + ((getTdValidDataId() == null) ? 0 : getTdValidDataId().hashCode());
        result = prime * result + ((getTdTime() == null) ? 0 : getTdTime().hashCode());
        result = prime * result + ((getQhzxReport() == null) ? 0 : getQhzxReport().hashCode());
        result = prime * result + ((getQhValidDataId() == null) ? 0 : getQhValidDataId().hashCode());
        result = prime * result + ((getQhzxTime() == null) ? 0 : getQhzxTime().hashCode());
        result = prime * result + ((getFormId() == null) ? 0 : getFormId().hashCode());
        result = prime * result + ((getAdviseAmount() == null) ? 0 : getAdviseAmount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getHeadOrgId() == null) ? 0 : getHeadOrgId().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        return result;
    }
}