package com.starsgroupchina.credit.bean.model;

import com.starsgroupchina.common.base.BaseExample;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample extends BaseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private String additionalWhere;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setAdditionalWhere(String additionalWhere) {
        this.additionalWhere = additionalWhere;
    }

    public String getAdditionalWhere() {
        return additionalWhere;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(Integer value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(Integer value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(Integer value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(Integer value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(Integer value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<Integer> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<Integer> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(Integer value1, Integer value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Integer> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Integer> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(Integer value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(Integer value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(Integer value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(Integer value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(Integer value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<Integer> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<Integer> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(Integer value1, Integer value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdIsNull() {
            addCriterion("policy_id is null");
            return (Criteria) this;
        }

        public Criteria andPolicyIdIsNotNull() {
            addCriterion("policy_id is not null");
            return (Criteria) this;
        }

        public Criteria andPolicyIdEqualTo(Integer value) {
            addCriterion("policy_id =", value, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdNotEqualTo(Integer value) {
            addCriterion("policy_id <>", value, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdGreaterThan(Integer value) {
            addCriterion("policy_id >", value, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("policy_id >=", value, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdLessThan(Integer value) {
            addCriterion("policy_id <", value, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdLessThanOrEqualTo(Integer value) {
            addCriterion("policy_id <=", value, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdIn(List<Integer> values) {
            addCriterion("policy_id in", values, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdNotIn(List<Integer> values) {
            addCriterion("policy_id not in", values, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdBetween(Integer value1, Integer value2) {
            addCriterion("policy_id between", value1, value2, "policyId");
            return (Criteria) this;
        }

        public Criteria andPolicyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("policy_id not between", value1, value2, "policyId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andAuditCrossIsNull() {
            addCriterion("audit_cross is null");
            return (Criteria) this;
        }

        public Criteria andAuditCrossIsNotNull() {
            addCriterion("audit_cross is not null");
            return (Criteria) this;
        }

        public Criteria andAuditCrossEqualTo(Short value) {
            addCriterion("audit_cross =", value, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossNotEqualTo(Short value) {
            addCriterion("audit_cross <>", value, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossGreaterThan(Short value) {
            addCriterion("audit_cross >", value, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossGreaterThanOrEqualTo(Short value) {
            addCriterion("audit_cross >=", value, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossLessThan(Short value) {
            addCriterion("audit_cross <", value, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossLessThanOrEqualTo(Short value) {
            addCriterion("audit_cross <=", value, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossIn(List<Short> values) {
            addCriterion("audit_cross in", values, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossNotIn(List<Short> values) {
            addCriterion("audit_cross not in", values, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossBetween(Short value1, Short value2) {
            addCriterion("audit_cross between", value1, value2, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditCrossNotBetween(Short value1, Short value2) {
            addCriterion("audit_cross not between", value1, value2, "auditCross");
            return (Criteria) this;
        }

        public Criteria andAuditAutoIsNull() {
            addCriterion("audit_auto is null");
            return (Criteria) this;
        }

        public Criteria andAuditAutoIsNotNull() {
            addCriterion("audit_auto is not null");
            return (Criteria) this;
        }

        public Criteria andAuditAutoEqualTo(Short value) {
            addCriterion("audit_auto =", value, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoNotEqualTo(Short value) {
            addCriterion("audit_auto <>", value, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoGreaterThan(Short value) {
            addCriterion("audit_auto >", value, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoGreaterThanOrEqualTo(Short value) {
            addCriterion("audit_auto >=", value, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoLessThan(Short value) {
            addCriterion("audit_auto <", value, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoLessThanOrEqualTo(Short value) {
            addCriterion("audit_auto <=", value, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoIn(List<Short> values) {
            addCriterion("audit_auto in", values, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoNotIn(List<Short> values) {
            addCriterion("audit_auto not in", values, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoBetween(Short value1, Short value2) {
            addCriterion("audit_auto between", value1, value2, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditAutoNotBetween(Short value1, Short value2) {
            addCriterion("audit_auto not between", value1, value2, "auditAuto");
            return (Criteria) this;
        }

        public Criteria andAuditManualIsNull() {
            addCriterion("audit_manual is null");
            return (Criteria) this;
        }

        public Criteria andAuditManualIsNotNull() {
            addCriterion("audit_manual is not null");
            return (Criteria) this;
        }

        public Criteria andAuditManualEqualTo(Short value) {
            addCriterion("audit_manual =", value, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualNotEqualTo(Short value) {
            addCriterion("audit_manual <>", value, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualGreaterThan(Short value) {
            addCriterion("audit_manual >", value, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualGreaterThanOrEqualTo(Short value) {
            addCriterion("audit_manual >=", value, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualLessThan(Short value) {
            addCriterion("audit_manual <", value, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualLessThanOrEqualTo(Short value) {
            addCriterion("audit_manual <=", value, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualIn(List<Short> values) {
            addCriterion("audit_manual in", values, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualNotIn(List<Short> values) {
            addCriterion("audit_manual not in", values, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualBetween(Short value1, Short value2) {
            addCriterion("audit_manual between", value1, value2, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualNotBetween(Short value1, Short value2) {
            addCriterion("audit_manual not between", value1, value2, "auditManual");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckIsNull() {
            addCriterion("audit_manual_recheck is null");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckIsNotNull() {
            addCriterion("audit_manual_recheck is not null");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckEqualTo(Short value) {
            addCriterion("audit_manual_recheck =", value, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckNotEqualTo(Short value) {
            addCriterion("audit_manual_recheck <>", value, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckGreaterThan(Short value) {
            addCriterion("audit_manual_recheck >", value, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckGreaterThanOrEqualTo(Short value) {
            addCriterion("audit_manual_recheck >=", value, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckLessThan(Short value) {
            addCriterion("audit_manual_recheck <", value, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckLessThanOrEqualTo(Short value) {
            addCriterion("audit_manual_recheck <=", value, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckIn(List<Short> values) {
            addCriterion("audit_manual_recheck in", values, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckNotIn(List<Short> values) {
            addCriterion("audit_manual_recheck not in", values, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckBetween(Short value1, Short value2) {
            addCriterion("audit_manual_recheck between", value1, value2, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditManualRecheckNotBetween(Short value1, Short value2) {
            addCriterion("audit_manual_recheck not between", value1, value2, "auditManualRecheck");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdIsNull() {
            addCriterion("audit_recheck_role_id is null");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdIsNotNull() {
            addCriterion("audit_recheck_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdEqualTo(Integer value) {
            addCriterion("audit_recheck_role_id =", value, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdNotEqualTo(Integer value) {
            addCriterion("audit_recheck_role_id <>", value, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdGreaterThan(Integer value) {
            addCriterion("audit_recheck_role_id >", value, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_recheck_role_id >=", value, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdLessThan(Integer value) {
            addCriterion("audit_recheck_role_id <", value, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("audit_recheck_role_id <=", value, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdIn(List<Integer> values) {
            addCriterion("audit_recheck_role_id in", values, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdNotIn(List<Integer> values) {
            addCriterion("audit_recheck_role_id not in", values, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("audit_recheck_role_id between", value1, value2, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_recheck_role_id not between", value1, value2, "auditRecheckRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdIsNull() {
            addCriterion("audit_role_id is null");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdIsNotNull() {
            addCriterion("audit_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdEqualTo(Integer value) {
            addCriterion("audit_role_id =", value, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdNotEqualTo(Integer value) {
            addCriterion("audit_role_id <>", value, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdGreaterThan(Integer value) {
            addCriterion("audit_role_id >", value, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_role_id >=", value, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdLessThan(Integer value) {
            addCriterion("audit_role_id <", value, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("audit_role_id <=", value, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdIn(List<Integer> values) {
            addCriterion("audit_role_id in", values, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdNotIn(List<Integer> values) {
            addCriterion("audit_role_id not in", values, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("audit_role_id between", value1, value2, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andAuditRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_role_id not between", value1, value2, "auditRoleId");
            return (Criteria) this;
        }

        public Criteria andDfTimeIsNull() {
            addCriterion("df_time is null");
            return (Criteria) this;
        }

        public Criteria andDfTimeIsNotNull() {
            addCriterion("df_time is not null");
            return (Criteria) this;
        }

        public Criteria andDfTimeEqualTo(Integer value) {
            addCriterion("df_time =", value, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeNotEqualTo(Integer value) {
            addCriterion("df_time <>", value, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeGreaterThan(Integer value) {
            addCriterion("df_time >", value, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("df_time >=", value, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeLessThan(Integer value) {
            addCriterion("df_time <", value, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeLessThanOrEqualTo(Integer value) {
            addCriterion("df_time <=", value, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeIn(List<Integer> values) {
            addCriterion("df_time in", values, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeNotIn(List<Integer> values) {
            addCriterion("df_time not in", values, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeBetween(Integer value1, Integer value2) {
            addCriterion("df_time between", value1, value2, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("df_time not between", value1, value2, "dfTime");
            return (Criteria) this;
        }

        public Criteria andDfReportIsNull() {
            addCriterion("df_report is null");
            return (Criteria) this;
        }

        public Criteria andDfReportIsNotNull() {
            addCriterion("df_report is not null");
            return (Criteria) this;
        }

        public Criteria andDfReportEqualTo(Short value) {
            addCriterion("df_report =", value, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportNotEqualTo(Short value) {
            addCriterion("df_report <>", value, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportGreaterThan(Short value) {
            addCriterion("df_report >", value, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportGreaterThanOrEqualTo(Short value) {
            addCriterion("df_report >=", value, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportLessThan(Short value) {
            addCriterion("df_report <", value, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportLessThanOrEqualTo(Short value) {
            addCriterion("df_report <=", value, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportIn(List<Short> values) {
            addCriterion("df_report in", values, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportNotIn(List<Short> values) {
            addCriterion("df_report not in", values, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportBetween(Short value1, Short value2) {
            addCriterion("df_report between", value1, value2, "dfReport");
            return (Criteria) this;
        }

        public Criteria andDfReportNotBetween(Short value1, Short value2) {
            addCriterion("df_report not between", value1, value2, "dfReport");
            return (Criteria) this;
        }

        public Criteria andTdReportIsNull() {
            addCriterion("td_report is null");
            return (Criteria) this;
        }

        public Criteria andTdReportIsNotNull() {
            addCriterion("td_report is not null");
            return (Criteria) this;
        }

        public Criteria andTdReportEqualTo(Short value) {
            addCriterion("td_report =", value, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportNotEqualTo(Short value) {
            addCriterion("td_report <>", value, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportGreaterThan(Short value) {
            addCriterion("td_report >", value, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportGreaterThanOrEqualTo(Short value) {
            addCriterion("td_report >=", value, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportLessThan(Short value) {
            addCriterion("td_report <", value, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportLessThanOrEqualTo(Short value) {
            addCriterion("td_report <=", value, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportIn(List<Short> values) {
            addCriterion("td_report in", values, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportNotIn(List<Short> values) {
            addCriterion("td_report not in", values, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportBetween(Short value1, Short value2) {
            addCriterion("td_report between", value1, value2, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdReportNotBetween(Short value1, Short value2) {
            addCriterion("td_report not between", value1, value2, "tdReport");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdIsNull() {
            addCriterion("td_valid_data_id is null");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdIsNotNull() {
            addCriterion("td_valid_data_id is not null");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdEqualTo(Integer value) {
            addCriterion("td_valid_data_id =", value, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdNotEqualTo(Integer value) {
            addCriterion("td_valid_data_id <>", value, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdGreaterThan(Integer value) {
            addCriterion("td_valid_data_id >", value, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("td_valid_data_id >=", value, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdLessThan(Integer value) {
            addCriterion("td_valid_data_id <", value, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdLessThanOrEqualTo(Integer value) {
            addCriterion("td_valid_data_id <=", value, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdIn(List<Integer> values) {
            addCriterion("td_valid_data_id in", values, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdNotIn(List<Integer> values) {
            addCriterion("td_valid_data_id not in", values, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdBetween(Integer value1, Integer value2) {
            addCriterion("td_valid_data_id between", value1, value2, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdValidDataIdNotBetween(Integer value1, Integer value2) {
            addCriterion("td_valid_data_id not between", value1, value2, "tdValidDataId");
            return (Criteria) this;
        }

        public Criteria andTdTimeIsNull() {
            addCriterion("td_time is null");
            return (Criteria) this;
        }

        public Criteria andTdTimeIsNotNull() {
            addCriterion("td_time is not null");
            return (Criteria) this;
        }

        public Criteria andTdTimeEqualTo(Integer value) {
            addCriterion("td_time =", value, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeNotEqualTo(Integer value) {
            addCriterion("td_time <>", value, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeGreaterThan(Integer value) {
            addCriterion("td_time >", value, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("td_time >=", value, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeLessThan(Integer value) {
            addCriterion("td_time <", value, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeLessThanOrEqualTo(Integer value) {
            addCriterion("td_time <=", value, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeIn(List<Integer> values) {
            addCriterion("td_time in", values, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeNotIn(List<Integer> values) {
            addCriterion("td_time not in", values, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeBetween(Integer value1, Integer value2) {
            addCriterion("td_time between", value1, value2, "tdTime");
            return (Criteria) this;
        }

        public Criteria andTdTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("td_time not between", value1, value2, "tdTime");
            return (Criteria) this;
        }

        public Criteria andQhzxReportIsNull() {
            addCriterion("qhzx_report is null");
            return (Criteria) this;
        }

        public Criteria andQhzxReportIsNotNull() {
            addCriterion("qhzx_report is not null");
            return (Criteria) this;
        }

        public Criteria andQhzxReportEqualTo(Short value) {
            addCriterion("qhzx_report =", value, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportNotEqualTo(Short value) {
            addCriterion("qhzx_report <>", value, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportGreaterThan(Short value) {
            addCriterion("qhzx_report >", value, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportGreaterThanOrEqualTo(Short value) {
            addCriterion("qhzx_report >=", value, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportLessThan(Short value) {
            addCriterion("qhzx_report <", value, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportLessThanOrEqualTo(Short value) {
            addCriterion("qhzx_report <=", value, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportIn(List<Short> values) {
            addCriterion("qhzx_report in", values, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportNotIn(List<Short> values) {
            addCriterion("qhzx_report not in", values, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportBetween(Short value1, Short value2) {
            addCriterion("qhzx_report between", value1, value2, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhzxReportNotBetween(Short value1, Short value2) {
            addCriterion("qhzx_report not between", value1, value2, "qhzxReport");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdIsNull() {
            addCriterion("qh_valid_data_id is null");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdIsNotNull() {
            addCriterion("qh_valid_data_id is not null");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdEqualTo(Integer value) {
            addCriterion("qh_valid_data_id =", value, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdNotEqualTo(Integer value) {
            addCriterion("qh_valid_data_id <>", value, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdGreaterThan(Integer value) {
            addCriterion("qh_valid_data_id >", value, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("qh_valid_data_id >=", value, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdLessThan(Integer value) {
            addCriterion("qh_valid_data_id <", value, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdLessThanOrEqualTo(Integer value) {
            addCriterion("qh_valid_data_id <=", value, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdIn(List<Integer> values) {
            addCriterion("qh_valid_data_id in", values, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdNotIn(List<Integer> values) {
            addCriterion("qh_valid_data_id not in", values, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdBetween(Integer value1, Integer value2) {
            addCriterion("qh_valid_data_id between", value1, value2, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhValidDataIdNotBetween(Integer value1, Integer value2) {
            addCriterion("qh_valid_data_id not between", value1, value2, "qhValidDataId");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeIsNull() {
            addCriterion("qhzx_time is null");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeIsNotNull() {
            addCriterion("qhzx_time is not null");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeEqualTo(Integer value) {
            addCriterion("qhzx_time =", value, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeNotEqualTo(Integer value) {
            addCriterion("qhzx_time <>", value, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeGreaterThan(Integer value) {
            addCriterion("qhzx_time >", value, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("qhzx_time >=", value, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeLessThan(Integer value) {
            addCriterion("qhzx_time <", value, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeLessThanOrEqualTo(Integer value) {
            addCriterion("qhzx_time <=", value, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeIn(List<Integer> values) {
            addCriterion("qhzx_time in", values, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeNotIn(List<Integer> values) {
            addCriterion("qhzx_time not in", values, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeBetween(Integer value1, Integer value2) {
            addCriterion("qhzx_time between", value1, value2, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andQhzxTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("qhzx_time not between", value1, value2, "qhzxTime");
            return (Criteria) this;
        }

        public Criteria andFormIdIsNull() {
            addCriterion("form_id is null");
            return (Criteria) this;
        }

        public Criteria andFormIdIsNotNull() {
            addCriterion("form_id is not null");
            return (Criteria) this;
        }

        public Criteria andFormIdEqualTo(Integer value) {
            addCriterion("form_id =", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotEqualTo(Integer value) {
            addCriterion("form_id <>", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdGreaterThan(Integer value) {
            addCriterion("form_id >", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("form_id >=", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdLessThan(Integer value) {
            addCriterion("form_id <", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdLessThanOrEqualTo(Integer value) {
            addCriterion("form_id <=", value, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdIn(List<Integer> values) {
            addCriterion("form_id in", values, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotIn(List<Integer> values) {
            addCriterion("form_id not in", values, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdBetween(Integer value1, Integer value2) {
            addCriterion("form_id between", value1, value2, "formId");
            return (Criteria) this;
        }

        public Criteria andFormIdNotBetween(Integer value1, Integer value2) {
            addCriterion("form_id not between", value1, value2, "formId");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountIsNull() {
            addCriterion("advise_amount is null");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountIsNotNull() {
            addCriterion("advise_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountEqualTo(Double value) {
            addCriterion("advise_amount =", value, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountNotEqualTo(Double value) {
            addCriterion("advise_amount <>", value, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountGreaterThan(Double value) {
            addCriterion("advise_amount >", value, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("advise_amount >=", value, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountLessThan(Double value) {
            addCriterion("advise_amount <", value, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountLessThanOrEqualTo(Double value) {
            addCriterion("advise_amount <=", value, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountIn(List<Double> values) {
            addCriterion("advise_amount in", values, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountNotIn(List<Double> values) {
            addCriterion("advise_amount not in", values, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountBetween(Double value1, Double value2) {
            addCriterion("advise_amount between", value1, value2, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andAdviseAmountNotBetween(Double value1, Double value2) {
            addCriterion("advise_amount not between", value1, value2, "adviseAmount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("modify_user is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("modify_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("modify_user =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("modify_user <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("modify_user >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("modify_user <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("modify_user <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("modify_user like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("modify_user not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("modify_user in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("modify_user not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("modify_user between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("modify_user not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdIsNull() {
            addCriterion("head_org_id is null");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdIsNotNull() {
            addCriterion("head_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdEqualTo(Integer value) {
            addCriterion("head_org_id =", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdNotEqualTo(Integer value) {
            addCriterion("head_org_id <>", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdGreaterThan(Integer value) {
            addCriterion("head_org_id >", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("head_org_id >=", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdLessThan(Integer value) {
            addCriterion("head_org_id <", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdLessThanOrEqualTo(Integer value) {
            addCriterion("head_org_id <=", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdIn(List<Integer> values) {
            addCriterion("head_org_id in", values, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdNotIn(List<Integer> values) {
            addCriterion("head_org_id not in", values, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdBetween(Integer value1, Integer value2) {
            addCriterion("head_org_id between", value1, value2, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("head_org_id not between", value1, value2, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("modify_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("modify_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Integer value) {
            addCriterion("modify_user_id =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Integer value) {
            addCriterion("modify_user_id <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Integer value) {
            addCriterion("modify_user_id >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Integer value) {
            addCriterion("modify_user_id <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Integer> values) {
            addCriterion("modify_user_id in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Integer> values) {
            addCriterion("modify_user_id not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}