package com.starsgroupchina.credit.bean.model;

import com.starsgroupchina.common.base.BaseExample;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectRiskDeclareRecordExample extends BaseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private String additionalWhere;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public ProjectRiskDeclareRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setAdditionalWhere(String additionalWhere) {
        this.additionalWhere = additionalWhere;
    }

    public String getAdditionalWhere() {
        return additionalWhere;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectNoIsNull() {
            addCriterion("project_no is null");
            return (Criteria) this;
        }

        public Criteria andProjectNoIsNotNull() {
            addCriterion("project_no is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNoEqualTo(String value) {
            addCriterion("project_no =", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotEqualTo(String value) {
            addCriterion("project_no <>", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoGreaterThan(String value) {
            addCriterion("project_no >", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoGreaterThanOrEqualTo(String value) {
            addCriterion("project_no >=", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoLessThan(String value) {
            addCriterion("project_no <", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoLessThanOrEqualTo(String value) {
            addCriterion("project_no <=", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoLike(String value) {
            addCriterion("project_no like", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotLike(String value) {
            addCriterion("project_no not like", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoIn(List<String> values) {
            addCriterion("project_no in", values, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotIn(List<String> values) {
            addCriterion("project_no not in", values, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoBetween(String value1, String value2) {
            addCriterion("project_no between", value1, value2, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotBetween(String value1, String value2) {
            addCriterion("project_no not between", value1, value2, "projectNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoIsNull() {
            addCriterion("declare_no is null");
            return (Criteria) this;
        }

        public Criteria andDeclareNoIsNotNull() {
            addCriterion("declare_no is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareNoEqualTo(String value) {
            addCriterion("declare_no =", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotEqualTo(String value) {
            addCriterion("declare_no <>", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoGreaterThan(String value) {
            addCriterion("declare_no >", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoGreaterThanOrEqualTo(String value) {
            addCriterion("declare_no >=", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoLessThan(String value) {
            addCriterion("declare_no <", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoLessThanOrEqualTo(String value) {
            addCriterion("declare_no <=", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoLike(String value) {
            addCriterion("declare_no like", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotLike(String value) {
            addCriterion("declare_no not like", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoIn(List<String> values) {
            addCriterion("declare_no in", values, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotIn(List<String> values) {
            addCriterion("declare_no not in", values, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoBetween(String value1, String value2) {
            addCriterion("declare_no between", value1, value2, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotBetween(String value1, String value2) {
            addCriterion("declare_no not between", value1, value2, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceIsNull() {
            addCriterion("declare_source is null");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceIsNotNull() {
            addCriterion("declare_source is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceEqualTo(Short value) {
            addCriterion("declare_source =", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceNotEqualTo(Short value) {
            addCriterion("declare_source <>", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceGreaterThan(Short value) {
            addCriterion("declare_source >", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceGreaterThanOrEqualTo(Short value) {
            addCriterion("declare_source >=", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceLessThan(Short value) {
            addCriterion("declare_source <", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceLessThanOrEqualTo(Short value) {
            addCriterion("declare_source <=", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceIn(List<Short> values) {
            addCriterion("declare_source in", values, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceNotIn(List<Short> values) {
            addCriterion("declare_source not in", values, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceBetween(Short value1, Short value2) {
            addCriterion("declare_source between", value1, value2, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceNotBetween(Short value1, Short value2) {
            addCriterion("declare_source not between", value1, value2, "declareSource");
            return (Criteria) this;
        }

        public Criteria andSurveyResultIsNull() {
            addCriterion("survey_result is null");
            return (Criteria) this;
        }

        public Criteria andSurveyResultIsNotNull() {
            addCriterion("survey_result is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyResultEqualTo(String value) {
            addCriterion("survey_result =", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultNotEqualTo(String value) {
            addCriterion("survey_result <>", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultGreaterThan(String value) {
            addCriterion("survey_result >", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultGreaterThanOrEqualTo(String value) {
            addCriterion("survey_result >=", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultLessThan(String value) {
            addCriterion("survey_result <", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultLessThanOrEqualTo(String value) {
            addCriterion("survey_result <=", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultLike(String value) {
            addCriterion("survey_result like", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultNotLike(String value) {
            addCriterion("survey_result not like", value, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultIn(List<String> values) {
            addCriterion("survey_result in", values, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultNotIn(List<String> values) {
            addCriterion("survey_result not in", values, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultBetween(String value1, String value2) {
            addCriterion("survey_result between", value1, value2, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyResultNotBetween(String value1, String value2) {
            addCriterion("survey_result not between", value1, value2, "surveyResult");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorIsNull() {
            addCriterion("survey_behavior is null");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorIsNotNull() {
            addCriterion("survey_behavior is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorEqualTo(String value) {
            addCriterion("survey_behavior =", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorNotEqualTo(String value) {
            addCriterion("survey_behavior <>", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorGreaterThan(String value) {
            addCriterion("survey_behavior >", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorGreaterThanOrEqualTo(String value) {
            addCriterion("survey_behavior >=", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorLessThan(String value) {
            addCriterion("survey_behavior <", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorLessThanOrEqualTo(String value) {
            addCriterion("survey_behavior <=", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorLike(String value) {
            addCriterion("survey_behavior like", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorNotLike(String value) {
            addCriterion("survey_behavior not like", value, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorIn(List<String> values) {
            addCriterion("survey_behavior in", values, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorNotIn(List<String> values) {
            addCriterion("survey_behavior not in", values, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorBetween(String value1, String value2) {
            addCriterion("survey_behavior between", value1, value2, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyBehaviorNotBetween(String value1, String value2) {
            addCriterion("survey_behavior not between", value1, value2, "surveyBehavior");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelIsNull() {
            addCriterion("survey_level is null");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelIsNotNull() {
            addCriterion("survey_level is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelEqualTo(String value) {
            addCriterion("survey_level =", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelNotEqualTo(String value) {
            addCriterion("survey_level <>", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelGreaterThan(String value) {
            addCriterion("survey_level >", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelGreaterThanOrEqualTo(String value) {
            addCriterion("survey_level >=", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelLessThan(String value) {
            addCriterion("survey_level <", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelLessThanOrEqualTo(String value) {
            addCriterion("survey_level <=", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelLike(String value) {
            addCriterion("survey_level like", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelNotLike(String value) {
            addCriterion("survey_level not like", value, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelIn(List<String> values) {
            addCriterion("survey_level in", values, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelNotIn(List<String> values) {
            addCriterion("survey_level not in", values, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelBetween(String value1, String value2) {
            addCriterion("survey_level between", value1, value2, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyLevelNotBetween(String value1, String value2) {
            addCriterion("survey_level not between", value1, value2, "surveyLevel");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkIsNull() {
            addCriterion("survey_remark is null");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkIsNotNull() {
            addCriterion("survey_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkEqualTo(String value) {
            addCriterion("survey_remark =", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkNotEqualTo(String value) {
            addCriterion("survey_remark <>", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkGreaterThan(String value) {
            addCriterion("survey_remark >", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("survey_remark >=", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkLessThan(String value) {
            addCriterion("survey_remark <", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkLessThanOrEqualTo(String value) {
            addCriterion("survey_remark <=", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkLike(String value) {
            addCriterion("survey_remark like", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkNotLike(String value) {
            addCriterion("survey_remark not like", value, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkIn(List<String> values) {
            addCriterion("survey_remark in", values, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkNotIn(List<String> values) {
            addCriterion("survey_remark not in", values, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkBetween(String value1, String value2) {
            addCriterion("survey_remark between", value1, value2, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andSurveyRemarkNotBetween(String value1, String value2) {
            addCriterion("survey_remark not between", value1, value2, "surveyRemark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("modify_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("modify_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Integer value) {
            addCriterion("modify_user_id =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Integer value) {
            addCriterion("modify_user_id <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Integer value) {
            addCriterion("modify_user_id >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Integer value) {
            addCriterion("modify_user_id <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Integer> values) {
            addCriterion("modify_user_id in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Integer> values) {
            addCriterion("modify_user_id not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("modify_user is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("modify_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("modify_user =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("modify_user <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("modify_user >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("modify_user <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("modify_user <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("modify_user like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("modify_user not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("modify_user in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("modify_user not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("modify_user between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("modify_user not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_risk_declare_record
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}