package com.starsgroupchina.credit.bean.model;

import com.starsgroupchina.common.base.BaseExample;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectRiskDeclareExample extends BaseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private String additionalWhere;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public ProjectRiskDeclareExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setAdditionalWhere(String additionalWhere) {
        this.additionalWhere = additionalWhere;
    }

    public String getAdditionalWhere() {
        return additionalWhere;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeclareNoIsNull() {
            addCriterion("declare_no is null");
            return (Criteria) this;
        }

        public Criteria andDeclareNoIsNotNull() {
            addCriterion("declare_no is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareNoEqualTo(String value) {
            addCriterion("declare_no =", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotEqualTo(String value) {
            addCriterion("declare_no <>", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoGreaterThan(String value) {
            addCriterion("declare_no >", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoGreaterThanOrEqualTo(String value) {
            addCriterion("declare_no >=", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoLessThan(String value) {
            addCriterion("declare_no <", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoLessThanOrEqualTo(String value) {
            addCriterion("declare_no <=", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoLike(String value) {
            addCriterion("declare_no like", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotLike(String value) {
            addCriterion("declare_no not like", value, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoIn(List<String> values) {
            addCriterion("declare_no in", values, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotIn(List<String> values) {
            addCriterion("declare_no not in", values, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoBetween(String value1, String value2) {
            addCriterion("declare_no between", value1, value2, "declareNo");
            return (Criteria) this;
        }

        public Criteria andDeclareNoNotBetween(String value1, String value2) {
            addCriterion("declare_no not between", value1, value2, "declareNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoIsNull() {
            addCriterion("project_no is null");
            return (Criteria) this;
        }

        public Criteria andProjectNoIsNotNull() {
            addCriterion("project_no is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNoEqualTo(String value) {
            addCriterion("project_no =", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotEqualTo(String value) {
            addCriterion("project_no <>", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoGreaterThan(String value) {
            addCriterion("project_no >", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoGreaterThanOrEqualTo(String value) {
            addCriterion("project_no >=", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoLessThan(String value) {
            addCriterion("project_no <", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoLessThanOrEqualTo(String value) {
            addCriterion("project_no <=", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoLike(String value) {
            addCriterion("project_no like", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotLike(String value) {
            addCriterion("project_no not like", value, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoIn(List<String> values) {
            addCriterion("project_no in", values, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotIn(List<String> values) {
            addCriterion("project_no not in", values, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoBetween(String value1, String value2) {
            addCriterion("project_no between", value1, value2, "projectNo");
            return (Criteria) this;
        }

        public Criteria andProjectNoNotBetween(String value1, String value2) {
            addCriterion("project_no not between", value1, value2, "projectNo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultIsNull() {
            addCriterion("first_survey_result is null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultIsNotNull() {
            addCriterion("first_survey_result is not null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultEqualTo(String value) {
            addCriterion("first_survey_result =", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultNotEqualTo(String value) {
            addCriterion("first_survey_result <>", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultGreaterThan(String value) {
            addCriterion("first_survey_result >", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultGreaterThanOrEqualTo(String value) {
            addCriterion("first_survey_result >=", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultLessThan(String value) {
            addCriterion("first_survey_result <", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultLessThanOrEqualTo(String value) {
            addCriterion("first_survey_result <=", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultLike(String value) {
            addCriterion("first_survey_result like", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultNotLike(String value) {
            addCriterion("first_survey_result not like", value, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultIn(List<String> values) {
            addCriterion("first_survey_result in", values, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultNotIn(List<String> values) {
            addCriterion("first_survey_result not in", values, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultBetween(String value1, String value2) {
            addCriterion("first_survey_result between", value1, value2, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyResultNotBetween(String value1, String value2) {
            addCriterion("first_survey_result not between", value1, value2, "firstSurveyResult");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorIsNull() {
            addCriterion("first_survey_behavior is null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorIsNotNull() {
            addCriterion("first_survey_behavior is not null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorEqualTo(String value) {
            addCriterion("first_survey_behavior =", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorNotEqualTo(String value) {
            addCriterion("first_survey_behavior <>", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorGreaterThan(String value) {
            addCriterion("first_survey_behavior >", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorGreaterThanOrEqualTo(String value) {
            addCriterion("first_survey_behavior >=", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorLessThan(String value) {
            addCriterion("first_survey_behavior <", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorLessThanOrEqualTo(String value) {
            addCriterion("first_survey_behavior <=", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorLike(String value) {
            addCriterion("first_survey_behavior like", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorNotLike(String value) {
            addCriterion("first_survey_behavior not like", value, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorIn(List<String> values) {
            addCriterion("first_survey_behavior in", values, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorNotIn(List<String> values) {
            addCriterion("first_survey_behavior not in", values, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorBetween(String value1, String value2) {
            addCriterion("first_survey_behavior between", value1, value2, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyBehaviorNotBetween(String value1, String value2) {
            addCriterion("first_survey_behavior not between", value1, value2, "firstSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelIsNull() {
            addCriterion("first_survey_level is null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelIsNotNull() {
            addCriterion("first_survey_level is not null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelEqualTo(String value) {
            addCriterion("first_survey_level =", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelNotEqualTo(String value) {
            addCriterion("first_survey_level <>", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelGreaterThan(String value) {
            addCriterion("first_survey_level >", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelGreaterThanOrEqualTo(String value) {
            addCriterion("first_survey_level >=", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelLessThan(String value) {
            addCriterion("first_survey_level <", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelLessThanOrEqualTo(String value) {
            addCriterion("first_survey_level <=", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelLike(String value) {
            addCriterion("first_survey_level like", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelNotLike(String value) {
            addCriterion("first_survey_level not like", value, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelIn(List<String> values) {
            addCriterion("first_survey_level in", values, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelNotIn(List<String> values) {
            addCriterion("first_survey_level not in", values, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelBetween(String value1, String value2) {
            addCriterion("first_survey_level between", value1, value2, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyLevelNotBetween(String value1, String value2) {
            addCriterion("first_survey_level not between", value1, value2, "firstSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkIsNull() {
            addCriterion("first_survey_remark is null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkIsNotNull() {
            addCriterion("first_survey_remark is not null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkEqualTo(String value) {
            addCriterion("first_survey_remark =", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkNotEqualTo(String value) {
            addCriterion("first_survey_remark <>", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkGreaterThan(String value) {
            addCriterion("first_survey_remark >", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("first_survey_remark >=", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkLessThan(String value) {
            addCriterion("first_survey_remark <", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkLessThanOrEqualTo(String value) {
            addCriterion("first_survey_remark <=", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkLike(String value) {
            addCriterion("first_survey_remark like", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkNotLike(String value) {
            addCriterion("first_survey_remark not like", value, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkIn(List<String> values) {
            addCriterion("first_survey_remark in", values, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkNotIn(List<String> values) {
            addCriterion("first_survey_remark not in", values, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkBetween(String value1, String value2) {
            addCriterion("first_survey_remark between", value1, value2, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyRemarkNotBetween(String value1, String value2) {
            addCriterion("first_survey_remark not between", value1, value2, "firstSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultIsNull() {
            addCriterion("two_survey_result is null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultIsNotNull() {
            addCriterion("two_survey_result is not null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultEqualTo(String value) {
            addCriterion("two_survey_result =", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultNotEqualTo(String value) {
            addCriterion("two_survey_result <>", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultGreaterThan(String value) {
            addCriterion("two_survey_result >", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultGreaterThanOrEqualTo(String value) {
            addCriterion("two_survey_result >=", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultLessThan(String value) {
            addCriterion("two_survey_result <", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultLessThanOrEqualTo(String value) {
            addCriterion("two_survey_result <=", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultLike(String value) {
            addCriterion("two_survey_result like", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultNotLike(String value) {
            addCriterion("two_survey_result not like", value, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultIn(List<String> values) {
            addCriterion("two_survey_result in", values, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultNotIn(List<String> values) {
            addCriterion("two_survey_result not in", values, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultBetween(String value1, String value2) {
            addCriterion("two_survey_result between", value1, value2, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyResultNotBetween(String value1, String value2) {
            addCriterion("two_survey_result not between", value1, value2, "twoSurveyResult");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorIsNull() {
            addCriterion("two_survey_behavior is null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorIsNotNull() {
            addCriterion("two_survey_behavior is not null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorEqualTo(String value) {
            addCriterion("two_survey_behavior =", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorNotEqualTo(String value) {
            addCriterion("two_survey_behavior <>", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorGreaterThan(String value) {
            addCriterion("two_survey_behavior >", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorGreaterThanOrEqualTo(String value) {
            addCriterion("two_survey_behavior >=", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorLessThan(String value) {
            addCriterion("two_survey_behavior <", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorLessThanOrEqualTo(String value) {
            addCriterion("two_survey_behavior <=", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorLike(String value) {
            addCriterion("two_survey_behavior like", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorNotLike(String value) {
            addCriterion("two_survey_behavior not like", value, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorIn(List<String> values) {
            addCriterion("two_survey_behavior in", values, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorNotIn(List<String> values) {
            addCriterion("two_survey_behavior not in", values, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorBetween(String value1, String value2) {
            addCriterion("two_survey_behavior between", value1, value2, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyBehaviorNotBetween(String value1, String value2) {
            addCriterion("two_survey_behavior not between", value1, value2, "twoSurveyBehavior");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelIsNull() {
            addCriterion("two_survey_level is null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelIsNotNull() {
            addCriterion("two_survey_level is not null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelEqualTo(String value) {
            addCriterion("two_survey_level =", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelNotEqualTo(String value) {
            addCriterion("two_survey_level <>", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelGreaterThan(String value) {
            addCriterion("two_survey_level >", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelGreaterThanOrEqualTo(String value) {
            addCriterion("two_survey_level >=", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelLessThan(String value) {
            addCriterion("two_survey_level <", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelLessThanOrEqualTo(String value) {
            addCriterion("two_survey_level <=", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelLike(String value) {
            addCriterion("two_survey_level like", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelNotLike(String value) {
            addCriterion("two_survey_level not like", value, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelIn(List<String> values) {
            addCriterion("two_survey_level in", values, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelNotIn(List<String> values) {
            addCriterion("two_survey_level not in", values, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelBetween(String value1, String value2) {
            addCriterion("two_survey_level between", value1, value2, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyLevelNotBetween(String value1, String value2) {
            addCriterion("two_survey_level not between", value1, value2, "twoSurveyLevel");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkIsNull() {
            addCriterion("two_survey_remark is null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkIsNotNull() {
            addCriterion("two_survey_remark is not null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkEqualTo(String value) {
            addCriterion("two_survey_remark =", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkNotEqualTo(String value) {
            addCriterion("two_survey_remark <>", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkGreaterThan(String value) {
            addCriterion("two_survey_remark >", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("two_survey_remark >=", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkLessThan(String value) {
            addCriterion("two_survey_remark <", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkLessThanOrEqualTo(String value) {
            addCriterion("two_survey_remark <=", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkLike(String value) {
            addCriterion("two_survey_remark like", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkNotLike(String value) {
            addCriterion("two_survey_remark not like", value, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkIn(List<String> values) {
            addCriterion("two_survey_remark in", values, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkNotIn(List<String> values) {
            addCriterion("two_survey_remark not in", values, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkBetween(String value1, String value2) {
            addCriterion("two_survey_remark between", value1, value2, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyRemarkNotBetween(String value1, String value2) {
            addCriterion("two_survey_remark not between", value1, value2, "twoSurveyRemark");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceIsNull() {
            addCriterion("declare_source is null");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceIsNotNull() {
            addCriterion("declare_source is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceEqualTo(Short value) {
            addCriterion("declare_source =", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceNotEqualTo(Short value) {
            addCriterion("declare_source <>", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceGreaterThan(Short value) {
            addCriterion("declare_source >", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceGreaterThanOrEqualTo(Short value) {
            addCriterion("declare_source >=", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceLessThan(Short value) {
            addCriterion("declare_source <", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceLessThanOrEqualTo(Short value) {
            addCriterion("declare_source <=", value, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceIn(List<Short> values) {
            addCriterion("declare_source in", values, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceNotIn(List<Short> values) {
            addCriterion("declare_source not in", values, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceBetween(Short value1, Short value2) {
            addCriterion("declare_source between", value1, value2, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareSourceNotBetween(Short value1, Short value2) {
            addCriterion("declare_source not between", value1, value2, "declareSource");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeIsNull() {
            addCriterion("declare_type is null");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeIsNotNull() {
            addCriterion("declare_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeEqualTo(String value) {
            addCriterion("declare_type =", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeNotEqualTo(String value) {
            addCriterion("declare_type <>", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeGreaterThan(String value) {
            addCriterion("declare_type >", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeGreaterThanOrEqualTo(String value) {
            addCriterion("declare_type >=", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeLessThan(String value) {
            addCriterion("declare_type <", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeLessThanOrEqualTo(String value) {
            addCriterion("declare_type <=", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeLike(String value) {
            addCriterion("declare_type like", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeNotLike(String value) {
            addCriterion("declare_type not like", value, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeIn(List<String> values) {
            addCriterion("declare_type in", values, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeNotIn(List<String> values) {
            addCriterion("declare_type not in", values, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeBetween(String value1, String value2) {
            addCriterion("declare_type between", value1, value2, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareTypeNotBetween(String value1, String value2) {
            addCriterion("declare_type not between", value1, value2, "declareType");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonIsNull() {
            addCriterion("declare_reason is null");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonIsNotNull() {
            addCriterion("declare_reason is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonEqualTo(String value) {
            addCriterion("declare_reason =", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonNotEqualTo(String value) {
            addCriterion("declare_reason <>", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonGreaterThan(String value) {
            addCriterion("declare_reason >", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonGreaterThanOrEqualTo(String value) {
            addCriterion("declare_reason >=", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonLessThan(String value) {
            addCriterion("declare_reason <", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonLessThanOrEqualTo(String value) {
            addCriterion("declare_reason <=", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonLike(String value) {
            addCriterion("declare_reason like", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonNotLike(String value) {
            addCriterion("declare_reason not like", value, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonIn(List<String> values) {
            addCriterion("declare_reason in", values, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonNotIn(List<String> values) {
            addCriterion("declare_reason not in", values, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonBetween(String value1, String value2) {
            addCriterion("declare_reason between", value1, value2, "declareReason");
            return (Criteria) this;
        }

        public Criteria andDeclareReasonNotBetween(String value1, String value2) {
            addCriterion("declare_reason not between", value1, value2, "declareReason");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdIsNull() {
            addCriterion("first_survey_user_id is null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdIsNotNull() {
            addCriterion("first_survey_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdEqualTo(Integer value) {
            addCriterion("first_survey_user_id =", value, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdNotEqualTo(Integer value) {
            addCriterion("first_survey_user_id <>", value, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdGreaterThan(Integer value) {
            addCriterion("first_survey_user_id >", value, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_survey_user_id >=", value, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdLessThan(Integer value) {
            addCriterion("first_survey_user_id <", value, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("first_survey_user_id <=", value, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdIn(List<Integer> values) {
            addCriterion("first_survey_user_id in", values, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdNotIn(List<Integer> values) {
            addCriterion("first_survey_user_id not in", values, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("first_survey_user_id between", value1, value2, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andFirstSurveyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("first_survey_user_id not between", value1, value2, "firstSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdIsNull() {
            addCriterion("two_survey_user_id is null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdIsNotNull() {
            addCriterion("two_survey_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdEqualTo(Integer value) {
            addCriterion("two_survey_user_id =", value, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdNotEqualTo(Integer value) {
            addCriterion("two_survey_user_id <>", value, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdGreaterThan(Integer value) {
            addCriterion("two_survey_user_id >", value, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("two_survey_user_id >=", value, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdLessThan(Integer value) {
            addCriterion("two_survey_user_id <", value, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("two_survey_user_id <=", value, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdIn(List<Integer> values) {
            addCriterion("two_survey_user_id in", values, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdNotIn(List<Integer> values) {
            addCriterion("two_survey_user_id not in", values, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("two_survey_user_id between", value1, value2, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andTwoSurveyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("two_survey_user_id not between", value1, value2, "twoSurveyUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdIsNull() {
            addCriterion("declare_user_id is null");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdIsNotNull() {
            addCriterion("declare_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdEqualTo(Integer value) {
            addCriterion("declare_user_id =", value, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdNotEqualTo(Integer value) {
            addCriterion("declare_user_id <>", value, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdGreaterThan(Integer value) {
            addCriterion("declare_user_id >", value, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("declare_user_id >=", value, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdLessThan(Integer value) {
            addCriterion("declare_user_id <", value, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("declare_user_id <=", value, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdIn(List<Integer> values) {
            addCriterion("declare_user_id in", values, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdNotIn(List<Integer> values) {
            addCriterion("declare_user_id not in", values, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdBetween(Integer value1, Integer value2) {
            addCriterion("declare_user_id between", value1, value2, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("declare_user_id not between", value1, value2, "declareUserId");
            return (Criteria) this;
        }

        public Criteria andDeclareDateIsNull() {
            addCriterion("declare_date is null");
            return (Criteria) this;
        }

        public Criteria andDeclareDateIsNotNull() {
            addCriterion("declare_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareDateEqualTo(Date value) {
            addCriterion("declare_date =", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateNotEqualTo(Date value) {
            addCriterion("declare_date <>", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateGreaterThan(Date value) {
            addCriterion("declare_date >", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateGreaterThanOrEqualTo(Date value) {
            addCriterion("declare_date >=", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateLessThan(Date value) {
            addCriterion("declare_date <", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateLessThanOrEqualTo(Date value) {
            addCriterion("declare_date <=", value, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateIn(List<Date> values) {
            addCriterion("declare_date in", values, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateNotIn(List<Date> values) {
            addCriterion("declare_date not in", values, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateBetween(Date value1, Date value2) {
            addCriterion("declare_date between", value1, value2, "declareDate");
            return (Criteria) this;
        }

        public Criteria andDeclareDateNotBetween(Date value1, Date value2) {
            addCriterion("declare_date not between", value1, value2, "declareDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("modify_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("modify_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Integer value) {
            addCriterion("modify_user_id =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Integer value) {
            addCriterion("modify_user_id <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Integer value) {
            addCriterion("modify_user_id >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Integer value) {
            addCriterion("modify_user_id <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Integer> values) {
            addCriterion("modify_user_id in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Integer> values) {
            addCriterion("modify_user_id not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("modify_user is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("modify_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("modify_user =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("modify_user <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("modify_user >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("modify_user <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("modify_user <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("modify_user like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("modify_user not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("modify_user in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("modify_user not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("modify_user between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("modify_user not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_risk_declare
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_risk_declare
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}