package com.starsgroupchina.credit.bean.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.starsgroupchina.common.base.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

@ApiModel
public class ProjectQualityResult extends BaseModel implements Serializable {
    @ApiModelProperty("id")
    private Integer id;

    @ApiModelProperty("项目编号")
    private String projectNo;

    @ApiModelProperty("审核错误类别")
    private String auditType;

    @ApiModelProperty("审核错误等级")
    private String auditLevel;

    @ApiModelProperty("审核备注")
    private String auditRemark;

    @ApiModelProperty("复核错误类别")
    private String auditRecheckType;

    @ApiModelProperty("复核错误等级")
    private String auditRecheckLevel;

    @ApiModelProperty("复核备注")
    private String auditRecheckRemark;

    @ApiModelProperty("状态0,正常，1禁用，-1删除")
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_quality_result
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getProjectNo() {
        return projectNo;
    }

    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    public String getAuditType() {
        return auditType;
    }

    public void setAuditType(String auditType) {
        this.auditType = auditType == null ? null : auditType.trim();
    }

    public String getAuditLevel() {
        return auditLevel;
    }

    public void setAuditLevel(String auditLevel) {
        this.auditLevel = auditLevel == null ? null : auditLevel.trim();
    }

    public String getAuditRemark() {
        return auditRemark;
    }

    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark == null ? null : auditRemark.trim();
    }

    public String getAuditRecheckType() {
        return auditRecheckType;
    }

    public void setAuditRecheckType(String auditRecheckType) {
        this.auditRecheckType = auditRecheckType == null ? null : auditRecheckType.trim();
    }

    public String getAuditRecheckLevel() {
        return auditRecheckLevel;
    }

    public void setAuditRecheckLevel(String auditRecheckLevel) {
        this.auditRecheckLevel = auditRecheckLevel == null ? null : auditRecheckLevel.trim();
    }

    public String getAuditRecheckRemark() {
        return auditRecheckRemark;
    }

    public void setAuditRecheckRemark(String auditRecheckRemark) {
        this.auditRecheckRemark = auditRecheckRemark == null ? null : auditRecheckRemark.trim();
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_quality_result
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        ProjectQualityResult other = (ProjectQualityResult) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProjectNo() == null ? other.getProjectNo() == null : this.getProjectNo().equals(other.getProjectNo()))
            && (this.getAuditType() == null ? other.getAuditType() == null : this.getAuditType().equals(other.getAuditType()))
            && (this.getAuditLevel() == null ? other.getAuditLevel() == null : this.getAuditLevel().equals(other.getAuditLevel()))
            && (this.getAuditRemark() == null ? other.getAuditRemark() == null : this.getAuditRemark().equals(other.getAuditRemark()))
            && (this.getAuditRecheckType() == null ? other.getAuditRecheckType() == null : this.getAuditRecheckType().equals(other.getAuditRecheckType()))
            && (this.getAuditRecheckLevel() == null ? other.getAuditRecheckLevel() == null : this.getAuditRecheckLevel().equals(other.getAuditRecheckLevel()))
            && (this.getAuditRecheckRemark() == null ? other.getAuditRecheckRemark() == null : this.getAuditRecheckRemark().equals(other.getAuditRecheckRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_quality_result
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjectNo() == null) ? 0 : getProjectNo().hashCode());
        result = prime * result + ((getAuditType() == null) ? 0 : getAuditType().hashCode());
        result = prime * result + ((getAuditLevel() == null) ? 0 : getAuditLevel().hashCode());
        result = prime * result + ((getAuditRemark() == null) ? 0 : getAuditRemark().hashCode());
        result = prime * result + ((getAuditRecheckType() == null) ? 0 : getAuditRecheckType().hashCode());
        result = prime * result + ((getAuditRecheckLevel() == null) ? 0 : getAuditRecheckLevel().hashCode());
        result = prime * result + ((getAuditRecheckRemark() == null) ? 0 : getAuditRecheckRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        return result;
    }
}