package com.starsgroupchina.credit.bean.model;

import com.starsgroupchina.common.base.BaseExample;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReportDayAuditExample extends BaseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private String additionalWhere;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public ReportDayAuditExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setAdditionalWhere(String additionalWhere) {
        this.additionalWhere = additionalWhere;
    }

    public String getAdditionalWhere() {
        return additionalWhere;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEntryNumIsNull() {
            addCriterion("entry_num is null");
            return (Criteria) this;
        }

        public Criteria andEntryNumIsNotNull() {
            addCriterion("entry_num is not null");
            return (Criteria) this;
        }

        public Criteria andEntryNumEqualTo(Integer value) {
            addCriterion("entry_num =", value, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumNotEqualTo(Integer value) {
            addCriterion("entry_num <>", value, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumGreaterThan(Integer value) {
            addCriterion("entry_num >", value, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("entry_num >=", value, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumLessThan(Integer value) {
            addCriterion("entry_num <", value, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumLessThanOrEqualTo(Integer value) {
            addCriterion("entry_num <=", value, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumIn(List<Integer> values) {
            addCriterion("entry_num in", values, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumNotIn(List<Integer> values) {
            addCriterion("entry_num not in", values, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumBetween(Integer value1, Integer value2) {
            addCriterion("entry_num between", value1, value2, "entryNum");
            return (Criteria) this;
        }

        public Criteria andEntryNumNotBetween(Integer value1, Integer value2) {
            addCriterion("entry_num not between", value1, value2, "entryNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumIsNull() {
            addCriterion("audit_handle_num is null");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumIsNotNull() {
            addCriterion("audit_handle_num is not null");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumEqualTo(Integer value) {
            addCriterion("audit_handle_num =", value, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumNotEqualTo(Integer value) {
            addCriterion("audit_handle_num <>", value, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumGreaterThan(Integer value) {
            addCriterion("audit_handle_num >", value, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_handle_num >=", value, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumLessThan(Integer value) {
            addCriterion("audit_handle_num <", value, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumLessThanOrEqualTo(Integer value) {
            addCriterion("audit_handle_num <=", value, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumIn(List<Integer> values) {
            addCriterion("audit_handle_num in", values, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumNotIn(List<Integer> values) {
            addCriterion("audit_handle_num not in", values, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumBetween(Integer value1, Integer value2) {
            addCriterion("audit_handle_num between", value1, value2, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditHandleNumNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_handle_num not between", value1, value2, "auditHandleNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumIsNull() {
            addCriterion("audit_attendance_num is null");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumIsNotNull() {
            addCriterion("audit_attendance_num is not null");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumEqualTo(Integer value) {
            addCriterion("audit_attendance_num =", value, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumNotEqualTo(Integer value) {
            addCriterion("audit_attendance_num <>", value, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumGreaterThan(Integer value) {
            addCriterion("audit_attendance_num >", value, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_attendance_num >=", value, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumLessThan(Integer value) {
            addCriterion("audit_attendance_num <", value, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumLessThanOrEqualTo(Integer value) {
            addCriterion("audit_attendance_num <=", value, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumIn(List<Integer> values) {
            addCriterion("audit_attendance_num in", values, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumNotIn(List<Integer> values) {
            addCriterion("audit_attendance_num not in", values, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumBetween(Integer value1, Integer value2) {
            addCriterion("audit_attendance_num between", value1, value2, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAttendanceNumNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_attendance_num not between", value1, value2, "auditAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumIsNull() {
            addCriterion("audit_average_num is null");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumIsNotNull() {
            addCriterion("audit_average_num is not null");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumEqualTo(Double value) {
            addCriterion("audit_average_num =", value, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumNotEqualTo(Double value) {
            addCriterion("audit_average_num <>", value, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumGreaterThan(Double value) {
            addCriterion("audit_average_num >", value, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumGreaterThanOrEqualTo(Double value) {
            addCriterion("audit_average_num >=", value, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumLessThan(Double value) {
            addCriterion("audit_average_num <", value, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumLessThanOrEqualTo(Double value) {
            addCriterion("audit_average_num <=", value, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumIn(List<Double> values) {
            addCriterion("audit_average_num in", values, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumNotIn(List<Double> values) {
            addCriterion("audit_average_num not in", values, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumBetween(Double value1, Double value2) {
            addCriterion("audit_average_num between", value1, value2, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditAverageNumNotBetween(Double value1, Double value2) {
            addCriterion("audit_average_num not between", value1, value2, "auditAverageNum");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateIsNull() {
            addCriterion("audit_treatment_rate is null");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateIsNotNull() {
            addCriterion("audit_treatment_rate is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateEqualTo(Double value) {
            addCriterion("audit_treatment_rate =", value, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateNotEqualTo(Double value) {
            addCriterion("audit_treatment_rate <>", value, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateGreaterThan(Double value) {
            addCriterion("audit_treatment_rate >", value, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateGreaterThanOrEqualTo(Double value) {
            addCriterion("audit_treatment_rate >=", value, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateLessThan(Double value) {
            addCriterion("audit_treatment_rate <", value, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateLessThanOrEqualTo(Double value) {
            addCriterion("audit_treatment_rate <=", value, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateIn(List<Double> values) {
            addCriterion("audit_treatment_rate in", values, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateNotIn(List<Double> values) {
            addCriterion("audit_treatment_rate not in", values, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateBetween(Double value1, Double value2) {
            addCriterion("audit_treatment_rate between", value1, value2, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andAuditTreatmentRateNotBetween(Double value1, Double value2) {
            addCriterion("audit_treatment_rate not between", value1, value2, "auditTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumIsNull() {
            addCriterion("recheck_handle_num is null");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumIsNotNull() {
            addCriterion("recheck_handle_num is not null");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumEqualTo(Integer value) {
            addCriterion("recheck_handle_num =", value, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumNotEqualTo(Integer value) {
            addCriterion("recheck_handle_num <>", value, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumGreaterThan(Integer value) {
            addCriterion("recheck_handle_num >", value, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("recheck_handle_num >=", value, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumLessThan(Integer value) {
            addCriterion("recheck_handle_num <", value, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumLessThanOrEqualTo(Integer value) {
            addCriterion("recheck_handle_num <=", value, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumIn(List<Integer> values) {
            addCriterion("recheck_handle_num in", values, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumNotIn(List<Integer> values) {
            addCriterion("recheck_handle_num not in", values, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumBetween(Integer value1, Integer value2) {
            addCriterion("recheck_handle_num between", value1, value2, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckHandleNumNotBetween(Integer value1, Integer value2) {
            addCriterion("recheck_handle_num not between", value1, value2, "recheckHandleNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumIsNull() {
            addCriterion("recheck_attendance_num is null");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumIsNotNull() {
            addCriterion("recheck_attendance_num is not null");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumEqualTo(Integer value) {
            addCriterion("recheck_attendance_num =", value, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumNotEqualTo(Integer value) {
            addCriterion("recheck_attendance_num <>", value, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumGreaterThan(Integer value) {
            addCriterion("recheck_attendance_num >", value, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("recheck_attendance_num >=", value, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumLessThan(Integer value) {
            addCriterion("recheck_attendance_num <", value, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumLessThanOrEqualTo(Integer value) {
            addCriterion("recheck_attendance_num <=", value, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumIn(List<Integer> values) {
            addCriterion("recheck_attendance_num in", values, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumNotIn(List<Integer> values) {
            addCriterion("recheck_attendance_num not in", values, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumBetween(Integer value1, Integer value2) {
            addCriterion("recheck_attendance_num between", value1, value2, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAttendanceNumNotBetween(Integer value1, Integer value2) {
            addCriterion("recheck_attendance_num not between", value1, value2, "recheckAttendanceNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumIsNull() {
            addCriterion("recheck_average_num is null");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumIsNotNull() {
            addCriterion("recheck_average_num is not null");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumEqualTo(Double value) {
            addCriterion("recheck_average_num =", value, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumNotEqualTo(Double value) {
            addCriterion("recheck_average_num <>", value, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumGreaterThan(Double value) {
            addCriterion("recheck_average_num >", value, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumGreaterThanOrEqualTo(Double value) {
            addCriterion("recheck_average_num >=", value, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumLessThan(Double value) {
            addCriterion("recheck_average_num <", value, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumLessThanOrEqualTo(Double value) {
            addCriterion("recheck_average_num <=", value, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumIn(List<Double> values) {
            addCriterion("recheck_average_num in", values, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumNotIn(List<Double> values) {
            addCriterion("recheck_average_num not in", values, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumBetween(Double value1, Double value2) {
            addCriterion("recheck_average_num between", value1, value2, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckAverageNumNotBetween(Double value1, Double value2) {
            addCriterion("recheck_average_num not between", value1, value2, "recheckAverageNum");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateIsNull() {
            addCriterion("recheck_treatment_rate is null");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateIsNotNull() {
            addCriterion("recheck_treatment_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateEqualTo(Double value) {
            addCriterion("recheck_treatment_rate =", value, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateNotEqualTo(Double value) {
            addCriterion("recheck_treatment_rate <>", value, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateGreaterThan(Double value) {
            addCriterion("recheck_treatment_rate >", value, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateGreaterThanOrEqualTo(Double value) {
            addCriterion("recheck_treatment_rate >=", value, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateLessThan(Double value) {
            addCriterion("recheck_treatment_rate <", value, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateLessThanOrEqualTo(Double value) {
            addCriterion("recheck_treatment_rate <=", value, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateIn(List<Double> values) {
            addCriterion("recheck_treatment_rate in", values, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateNotIn(List<Double> values) {
            addCriterion("recheck_treatment_rate not in", values, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateBetween(Double value1, Double value2) {
            addCriterion("recheck_treatment_rate between", value1, value2, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andRecheckTreatmentRateNotBetween(Double value1, Double value2) {
            addCriterion("recheck_treatment_rate not between", value1, value2, "recheckTreatmentRate");
            return (Criteria) this;
        }

        public Criteria andPendingIsNull() {
            addCriterion("pending is null");
            return (Criteria) this;
        }

        public Criteria andPendingIsNotNull() {
            addCriterion("pending is not null");
            return (Criteria) this;
        }

        public Criteria andPendingEqualTo(Integer value) {
            addCriterion("pending =", value, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingNotEqualTo(Integer value) {
            addCriterion("pending <>", value, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingGreaterThan(Integer value) {
            addCriterion("pending >", value, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingGreaterThanOrEqualTo(Integer value) {
            addCriterion("pending >=", value, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingLessThan(Integer value) {
            addCriterion("pending <", value, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingLessThanOrEqualTo(Integer value) {
            addCriterion("pending <=", value, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingIn(List<Integer> values) {
            addCriterion("pending in", values, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingNotIn(List<Integer> values) {
            addCriterion("pending not in", values, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingBetween(Integer value1, Integer value2) {
            addCriterion("pending between", value1, value2, "pending");
            return (Criteria) this;
        }

        public Criteria andPendingNotBetween(Integer value1, Integer value2) {
            addCriterion("pending not between", value1, value2, "pending");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("modify_user is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("modify_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("modify_user =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("modify_user <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("modify_user >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("modify_user <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("modify_user <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("modify_user like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("modify_user not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("modify_user in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("modify_user not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("modify_user between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("modify_user not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("modify_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("modify_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Integer value) {
            addCriterion("modify_user_id =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Integer value) {
            addCriterion("modify_user_id <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Integer value) {
            addCriterion("modify_user_id >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Integer value) {
            addCriterion("modify_user_id <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Integer> values) {
            addCriterion("modify_user_id in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Integer> values) {
            addCriterion("modify_user_id not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_day_audit
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_day_audit
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}