package com.starsgroupchina.credit.bean.model;

import com.starsgroupchina.common.base.BaseExample;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleExample extends BaseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private String additionalWhere;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public RoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setAdditionalWhere(String additionalWhere) {
        this.additionalWhere = additionalWhere;
    }

    public String getAdditionalWhere() {
        return additionalWhere;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdIsNull() {
            addCriterion("head_org_id is null");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdIsNotNull() {
            addCriterion("head_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdEqualTo(Integer value) {
            addCriterion("head_org_id =", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdNotEqualTo(Integer value) {
            addCriterion("head_org_id <>", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdGreaterThan(Integer value) {
            addCriterion("head_org_id >", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("head_org_id >=", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdLessThan(Integer value) {
            addCriterion("head_org_id <", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdLessThanOrEqualTo(Integer value) {
            addCriterion("head_org_id <=", value, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdIn(List<Integer> values) {
            addCriterion("head_org_id in", values, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdNotIn(List<Integer> values) {
            addCriterion("head_org_id not in", values, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdBetween(Integer value1, Integer value2) {
            addCriterion("head_org_id between", value1, value2, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andHeadOrgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("head_org_id not between", value1, value2, "headOrgId");
            return (Criteria) this;
        }

        public Criteria andAuthOperationIsNull() {
            addCriterion("auth_operation is null");
            return (Criteria) this;
        }

        public Criteria andAuthOperationIsNotNull() {
            addCriterion("auth_operation is not null");
            return (Criteria) this;
        }

        public Criteria andAuthOperationEqualTo(String value) {
            addCriterion("auth_operation =", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationNotEqualTo(String value) {
            addCriterion("auth_operation <>", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationGreaterThan(String value) {
            addCriterion("auth_operation >", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationGreaterThanOrEqualTo(String value) {
            addCriterion("auth_operation >=", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationLessThan(String value) {
            addCriterion("auth_operation <", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationLessThanOrEqualTo(String value) {
            addCriterion("auth_operation <=", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationLike(String value) {
            addCriterion("auth_operation like", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationNotLike(String value) {
            addCriterion("auth_operation not like", value, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationIn(List<String> values) {
            addCriterion("auth_operation in", values, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationNotIn(List<String> values) {
            addCriterion("auth_operation not in", values, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationBetween(String value1, String value2) {
            addCriterion("auth_operation between", value1, value2, "authOperation");
            return (Criteria) this;
        }

        public Criteria andAuthOperationNotBetween(String value1, String value2) {
            addCriterion("auth_operation not between", value1, value2, "authOperation");
            return (Criteria) this;
        }

        public Criteria andIsAuditIsNull() {
            addCriterion("is_audit is null");
            return (Criteria) this;
        }

        public Criteria andIsAuditIsNotNull() {
            addCriterion("is_audit is not null");
            return (Criteria) this;
        }

        public Criteria andIsAuditEqualTo(Integer value) {
            addCriterion("is_audit =", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditNotEqualTo(Integer value) {
            addCriterion("is_audit <>", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditGreaterThan(Integer value) {
            addCriterion("is_audit >", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_audit >=", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditLessThan(Integer value) {
            addCriterion("is_audit <", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditLessThanOrEqualTo(Integer value) {
            addCriterion("is_audit <=", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditIn(List<Integer> values) {
            addCriterion("is_audit in", values, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditNotIn(List<Integer> values) {
            addCriterion("is_audit not in", values, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditBetween(Integer value1, Integer value2) {
            addCriterion("is_audit between", value1, value2, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("is_audit not between", value1, value2, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckIsNull() {
            addCriterion("is_audit_recheck is null");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckIsNotNull() {
            addCriterion("is_audit_recheck is not null");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckEqualTo(Integer value) {
            addCriterion("is_audit_recheck =", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckNotEqualTo(Integer value) {
            addCriterion("is_audit_recheck <>", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckGreaterThan(Integer value) {
            addCriterion("is_audit_recheck >", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_audit_recheck >=", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckLessThan(Integer value) {
            addCriterion("is_audit_recheck <", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckLessThanOrEqualTo(Integer value) {
            addCriterion("is_audit_recheck <=", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckIn(List<Integer> values) {
            addCriterion("is_audit_recheck in", values, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckNotIn(List<Integer> values) {
            addCriterion("is_audit_recheck not in", values, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckBetween(Integer value1, Integer value2) {
            addCriterion("is_audit_recheck between", value1, value2, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckNotBetween(Integer value1, Integer value2) {
            addCriterion("is_audit_recheck not between", value1, value2, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsCheatIsNull() {
            addCriterion("is_cheat is null");
            return (Criteria) this;
        }

        public Criteria andIsCheatIsNotNull() {
            addCriterion("is_cheat is not null");
            return (Criteria) this;
        }

        public Criteria andIsCheatEqualTo(Integer value) {
            addCriterion("is_cheat =", value, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatNotEqualTo(Integer value) {
            addCriterion("is_cheat <>", value, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatGreaterThan(Integer value) {
            addCriterion("is_cheat >", value, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_cheat >=", value, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatLessThan(Integer value) {
            addCriterion("is_cheat <", value, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatLessThanOrEqualTo(Integer value) {
            addCriterion("is_cheat <=", value, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatIn(List<Integer> values) {
            addCriterion("is_cheat in", values, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatNotIn(List<Integer> values) {
            addCriterion("is_cheat not in", values, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatBetween(Integer value1, Integer value2) {
            addCriterion("is_cheat between", value1, value2, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsCheatNotBetween(Integer value1, Integer value2) {
            addCriterion("is_cheat not between", value1, value2, "isCheat");
            return (Criteria) this;
        }

        public Criteria andIsQualityIsNull() {
            addCriterion("is_quality is null");
            return (Criteria) this;
        }

        public Criteria andIsQualityIsNotNull() {
            addCriterion("is_quality is not null");
            return (Criteria) this;
        }

        public Criteria andIsQualityEqualTo(Integer value) {
            addCriterion("is_quality =", value, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityNotEqualTo(Integer value) {
            addCriterion("is_quality <>", value, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityGreaterThan(Integer value) {
            addCriterion("is_quality >", value, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_quality >=", value, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityLessThan(Integer value) {
            addCriterion("is_quality <", value, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityLessThanOrEqualTo(Integer value) {
            addCriterion("is_quality <=", value, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityIn(List<Integer> values) {
            addCriterion("is_quality in", values, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityNotIn(List<Integer> values) {
            addCriterion("is_quality not in", values, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityBetween(Integer value1, Integer value2) {
            addCriterion("is_quality between", value1, value2, "isQuality");
            return (Criteria) this;
        }

        public Criteria andIsQualityNotBetween(Integer value1, Integer value2) {
            addCriterion("is_quality not between", value1, value2, "isQuality");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderIsNull() {
            addCriterion("audit_leader is null");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderIsNotNull() {
            addCriterion("audit_leader is not null");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderEqualTo(String value) {
            addCriterion("audit_leader =", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderNotEqualTo(String value) {
            addCriterion("audit_leader <>", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderGreaterThan(String value) {
            addCriterion("audit_leader >", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("audit_leader >=", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderLessThan(String value) {
            addCriterion("audit_leader <", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderLessThanOrEqualTo(String value) {
            addCriterion("audit_leader <=", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderLike(String value) {
            addCriterion("audit_leader like", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderNotLike(String value) {
            addCriterion("audit_leader not like", value, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderIn(List<String> values) {
            addCriterion("audit_leader in", values, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderNotIn(List<String> values) {
            addCriterion("audit_leader not in", values, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderBetween(String value1, String value2) {
            addCriterion("audit_leader between", value1, value2, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditLeaderNotBetween(String value1, String value2) {
            addCriterion("audit_leader not between", value1, value2, "auditLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderIsNull() {
            addCriterion("audit_recheck_leader is null");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderIsNotNull() {
            addCriterion("audit_recheck_leader is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderEqualTo(String value) {
            addCriterion("audit_recheck_leader =", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderNotEqualTo(String value) {
            addCriterion("audit_recheck_leader <>", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderGreaterThan(String value) {
            addCriterion("audit_recheck_leader >", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("audit_recheck_leader >=", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderLessThan(String value) {
            addCriterion("audit_recheck_leader <", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderLessThanOrEqualTo(String value) {
            addCriterion("audit_recheck_leader <=", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderLike(String value) {
            addCriterion("audit_recheck_leader like", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderNotLike(String value) {
            addCriterion("audit_recheck_leader not like", value, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderIn(List<String> values) {
            addCriterion("audit_recheck_leader in", values, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderNotIn(List<String> values) {
            addCriterion("audit_recheck_leader not in", values, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderBetween(String value1, String value2) {
            addCriterion("audit_recheck_leader between", value1, value2, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckLeaderNotBetween(String value1, String value2) {
            addCriterion("audit_recheck_leader not between", value1, value2, "auditRecheckLeader");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("modify_user is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("modify_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("modify_user =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("modify_user <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("modify_user >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("modify_user <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("modify_user <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("modify_user like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("modify_user not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("modify_user in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("modify_user not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("modify_user between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("modify_user not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("modify_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("modify_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Integer value) {
            addCriterion("modify_user_id =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Integer value) {
            addCriterion("modify_user_id <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Integer value) {
            addCriterion("modify_user_id >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Integer value) {
            addCriterion("modify_user_id <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("modify_user_id <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Integer> values) {
            addCriterion("modify_user_id in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Integer> values) {
            addCriterion("modify_user_id not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_user_id not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}