package com.starsgroupchina.credit.bean.model;

import com.starsgroupchina.common.base.BaseExample;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VReportAchievementExample extends BaseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private String additionalWhere;

    private Integer limit;

    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public VReportAchievementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setAdditionalWhere(String additionalWhere) {
        this.additionalWhere = additionalWhere;
    }

    public String getAdditionalWhere() {
        return additionalWhere;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("login_name is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("login_name =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("login_name <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("login_name >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("login_name >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("login_name <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("login_name <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("login_name like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("login_name not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("login_name in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("login_name not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("login_name between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("login_name not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andIsAuditIsNull() {
            addCriterion("is_audit is null");
            return (Criteria) this;
        }

        public Criteria andIsAuditIsNotNull() {
            addCriterion("is_audit is not null");
            return (Criteria) this;
        }

        public Criteria andIsAuditEqualTo(Integer value) {
            addCriterion("is_audit =", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditNotEqualTo(Integer value) {
            addCriterion("is_audit <>", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditGreaterThan(Integer value) {
            addCriterion("is_audit >", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_audit >=", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditLessThan(Integer value) {
            addCriterion("is_audit <", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditLessThanOrEqualTo(Integer value) {
            addCriterion("is_audit <=", value, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditIn(List<Integer> values) {
            addCriterion("is_audit in", values, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditNotIn(List<Integer> values) {
            addCriterion("is_audit not in", values, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditBetween(Integer value1, Integer value2) {
            addCriterion("is_audit between", value1, value2, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("is_audit not between", value1, value2, "isAudit");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckIsNull() {
            addCriterion("is_audit_recheck is null");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckIsNotNull() {
            addCriterion("is_audit_recheck is not null");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckEqualTo(Integer value) {
            addCriterion("is_audit_recheck =", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckNotEqualTo(Integer value) {
            addCriterion("is_audit_recheck <>", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckGreaterThan(Integer value) {
            addCriterion("is_audit_recheck >", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_audit_recheck >=", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckLessThan(Integer value) {
            addCriterion("is_audit_recheck <", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckLessThanOrEqualTo(Integer value) {
            addCriterion("is_audit_recheck <=", value, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckIn(List<Integer> values) {
            addCriterion("is_audit_recheck in", values, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckNotIn(List<Integer> values) {
            addCriterion("is_audit_recheck not in", values, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckBetween(Integer value1, Integer value2) {
            addCriterion("is_audit_recheck between", value1, value2, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andIsAuditRecheckNotBetween(Integer value1, Integer value2) {
            addCriterion("is_audit_recheck not between", value1, value2, "isAuditRecheck");
            return (Criteria) this;
        }

        public Criteria andMobMonthIsNull() {
            addCriterion("mob_month is null");
            return (Criteria) this;
        }

        public Criteria andMobMonthIsNotNull() {
            addCriterion("mob_month is not null");
            return (Criteria) this;
        }

        public Criteria andMobMonthEqualTo(Integer value) {
            addCriterion("mob_month =", value, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthNotEqualTo(Integer value) {
            addCriterion("mob_month <>", value, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthGreaterThan(Integer value) {
            addCriterion("mob_month >", value, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("mob_month >=", value, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthLessThan(Integer value) {
            addCriterion("mob_month <", value, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthLessThanOrEqualTo(Integer value) {
            addCriterion("mob_month <=", value, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthIn(List<Integer> values) {
            addCriterion("mob_month in", values, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthNotIn(List<Integer> values) {
            addCriterion("mob_month not in", values, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthBetween(Integer value1, Integer value2) {
            addCriterion("mob_month between", value1, value2, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andMobMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("mob_month not between", value1, value2, "mobMonth");
            return (Criteria) this;
        }

        public Criteria andLoginDateIsNull() {
            addCriterion("login_date is null");
            return (Criteria) this;
        }

        public Criteria andLoginDateIsNotNull() {
            addCriterion("login_date is not null");
            return (Criteria) this;
        }

        public Criteria andLoginDateEqualTo(Date value) {
            addCriterionForJDBCDate("login_date =", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("login_date <>", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateGreaterThan(Date value) {
            addCriterionForJDBCDate("login_date >", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("login_date >=", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateLessThan(Date value) {
            addCriterionForJDBCDate("login_date <", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("login_date <=", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateIn(List<Date> values) {
            addCriterionForJDBCDate("login_date in", values, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("login_date not in", values, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("login_date between", value1, value2, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("login_date not between", value1, value2, "loginDate");
            return (Criteria) this;
        }

        public Criteria andAuditCountIsNull() {
            addCriterion("audit_count is null");
            return (Criteria) this;
        }

        public Criteria andAuditCountIsNotNull() {
            addCriterion("audit_count is not null");
            return (Criteria) this;
        }

        public Criteria andAuditCountEqualTo(Long value) {
            addCriterion("audit_count =", value, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountNotEqualTo(Long value) {
            addCriterion("audit_count <>", value, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountGreaterThan(Long value) {
            addCriterion("audit_count >", value, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountGreaterThanOrEqualTo(Long value) {
            addCriterion("audit_count >=", value, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountLessThan(Long value) {
            addCriterion("audit_count <", value, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountLessThanOrEqualTo(Long value) {
            addCriterion("audit_count <=", value, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountIn(List<Long> values) {
            addCriterion("audit_count in", values, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountNotIn(List<Long> values) {
            addCriterion("audit_count not in", values, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountBetween(Long value1, Long value2) {
            addCriterion("audit_count between", value1, value2, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditCountNotBetween(Long value1, Long value2) {
            addCriterion("audit_count not between", value1, value2, "auditCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountIsNull() {
            addCriterion("audit_recheck_count is null");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountIsNotNull() {
            addCriterion("audit_recheck_count is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountEqualTo(Long value) {
            addCriterion("audit_recheck_count =", value, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountNotEqualTo(Long value) {
            addCriterion("audit_recheck_count <>", value, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountGreaterThan(Long value) {
            addCriterion("audit_recheck_count >", value, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountGreaterThanOrEqualTo(Long value) {
            addCriterion("audit_recheck_count >=", value, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountLessThan(Long value) {
            addCriterion("audit_recheck_count <", value, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountLessThanOrEqualTo(Long value) {
            addCriterion("audit_recheck_count <=", value, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountIn(List<Long> values) {
            addCriterion("audit_recheck_count in", values, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountNotIn(List<Long> values) {
            addCriterion("audit_recheck_count not in", values, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountBetween(Long value1, Long value2) {
            addCriterion("audit_recheck_count between", value1, value2, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditRecheckCountNotBetween(Long value1, Long value2) {
            addCriterion("audit_recheck_count not between", value1, value2, "auditRecheckCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountIsNull() {
            addCriterion("audit_qua_count is null");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountIsNotNull() {
            addCriterion("audit_qua_count is not null");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountEqualTo(Long value) {
            addCriterion("audit_qua_count =", value, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountNotEqualTo(Long value) {
            addCriterion("audit_qua_count <>", value, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountGreaterThan(Long value) {
            addCriterion("audit_qua_count >", value, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountGreaterThanOrEqualTo(Long value) {
            addCriterion("audit_qua_count >=", value, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountLessThan(Long value) {
            addCriterion("audit_qua_count <", value, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountLessThanOrEqualTo(Long value) {
            addCriterion("audit_qua_count <=", value, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountIn(List<Long> values) {
            addCriterion("audit_qua_count in", values, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountNotIn(List<Long> values) {
            addCriterion("audit_qua_count not in", values, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountBetween(Long value1, Long value2) {
            addCriterion("audit_qua_count between", value1, value2, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andAuditQuaCountNotBetween(Long value1, Long value2) {
            addCriterion("audit_qua_count not between", value1, value2, "auditQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountIsNull() {
            addCriterion("recheck_qua_count is null");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountIsNotNull() {
            addCriterion("recheck_qua_count is not null");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountEqualTo(Long value) {
            addCriterion("recheck_qua_count =", value, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountNotEqualTo(Long value) {
            addCriterion("recheck_qua_count <>", value, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountGreaterThan(Long value) {
            addCriterion("recheck_qua_count >", value, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountGreaterThanOrEqualTo(Long value) {
            addCriterion("recheck_qua_count >=", value, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountLessThan(Long value) {
            addCriterion("recheck_qua_count <", value, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountLessThanOrEqualTo(Long value) {
            addCriterion("recheck_qua_count <=", value, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountIn(List<Long> values) {
            addCriterion("recheck_qua_count in", values, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountNotIn(List<Long> values) {
            addCriterion("recheck_qua_count not in", values, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountBetween(Long value1, Long value2) {
            addCriterion("recheck_qua_count between", value1, value2, "recheckQuaCount");
            return (Criteria) this;
        }

        public Criteria andRecheckQuaCountNotBetween(Long value1, Long value2) {
            addCriterion("recheck_qua_count not between", value1, value2, "recheckQuaCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_report_achievement
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_report_achievement
     *
     * @mbg.generated Wed Dec 19 16:26:10 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}