package com.starsgroupchina.credit.bean.third;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;

@ApiModel
@Data
public class ThirdCreditTdAddress implements Serializable {

    @ApiModelProperty("身份证所属地")
    private String idCardAddress;

    @ApiModelProperty("ip所属地")
    private String trueIpAddress;

    @ApiModelProperty("wifi所属地")
    private String wifiAddress;

    @ApiModelProperty("基站所属地")
    private String cellAddress;

    @ApiModelProperty("银行卡所属地")
    private String bankCardAddress;

    @ApiModelProperty("手机所属地")
    private String mobileAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zc_credit_td_address
     *
     * @mbggenerated Tue Jun 12 09:19:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

}